olm/open-liberty-0.0.1.clusterserviceversion.yaml

I modified the CSV to allow it to install on OKD 3.x.  I haven't tried to create an OpenLiberty object yet, but the operator starts up OK.
OKD required a minimum kubernetes version in the spec of the CSV.  I picked 1.11.0 since that's what I had, but, I suspect it can be lower than that.  I'm not sure how we test that part.  I remember reading somewhere that published operators should support at least 1.7.
The name 'openliberties.openliberty.io' needed to match the CRD.  I suspect that's why the operator "wasn't working" before the conversion to CSV.
The other sections (install, deployments, etc) were just missing and seemed like they were required based on other operators in the repository.  I used the values from the other .yaml files that we had, and just copied them into the CSV.

Edit CSV to allow install on OKD 3.11

---

build/Dockerfile

The newest SDK uses a newer operator image

Updating Dockerfile to newer version

---

olm/open-liberty-0.0.1.clusterserviceversion.yaml

Fixes #14 
I compared the base set of roles with other operators in the community and it appears the permissions are consistent.  I would have thought less access would be required, but for example, the operator needs to create a deployment, as well as delete a deployment, as well as list the deployments so it can figure out if an appropriate deployment already exists.
I synced the RBAC permissions with the CSV permissions.  Some things were missing (ingress, batch, autoscaling).

Sync up the CSV with the RBAC file

---

olm/open-liberty-0.0.1.clusterserviceversion.yaml

Changed some descriptions so that the field makes sense on the OKD console.
For example, the IIOP port was just labled "PORT" which was confusing (which
port?).  This deviates from the ICP/HELM labels, but the existing labels
were not useful in OKD.
The big change here though was removing the fields that returned complex types or empty objects, because those cause the OKD 4.x GUI (console) to crash when it tries to display them.  There is a "react" error.  For some reason the 3.x console is not affected.

Removed spec descriptors that caused the OKD 4.x GUI to crash.

---

olm/open-liberty.0.0.1.clusterserviceversion.yaml

It looks like there is a new category that is a better fit for us - Application Runtime.

Change the category to "Application Runtime"

---

deploy/dashboards/metrics/ibm-websphere-liberty-grafana-dashboard-metrics-2.0.json
deploy/dashboards/metrics/ibm-websphere-liberty-grafana-dashboard.json

- Changed filter to sort by **services** instead of by **app**
- Changed legend to display "service: \<my service\>" as opposed to "app: \<my app\>"
- Added 2 decimal places to value attribute of Maximum Heap Size visualization

Updated mpMetrics 1.1 and 2.0 Grafana dashboards

---

.travis.yml

- Removes the push stage from travis
- Now that we're building multi-arch images from GHE we should no longer be pushing from this repo, as it will overwrite the manifest list that's now being created.

Remove push stage from travis

---

doc/user-guide.md

- Where applicable point to the generic operator, and modify existing
docs to better document that relationship.
- Update the serviceability documentation to include example usage and separate it from the generic operator documentation.
-  Copy over updates to `env` and `envFrom` field descriptions in the CR field table from [appsody](https://github.com/appsody/appsody-operator/pull/216).
- Removed the `stack` field description from the table, as I don't believe it's supposed to be there.
Fixes #107

Modify user-guide to point to application-stacks

---

pkg/controller/openliberty/openlibertyapplication_controller.go

Make StatefulSet /  Deployment predicate check for generation to minimize number of reconciles

Add generation check for deployment/statefulset watch

---

doc/user-guide.adoc
pkg/utils/register.go
pkg/utils/utils.go

Fixes several problems found in testing of oidc autoregistration of the operator.
- some field names in the userguide were wrong.
- added sample secret to userguide to clarify how to compose the secret
- registration data could be lost if an error occured when registering multiple providers.
- write secret before aborting to preserve partial registration data 
- updated messages to use correct field names and added some logging 
- [x ] User guide
Fixes #177 #176

updates from auto-registration testing

---

deploy/olm-catalog/open-liberty-operator-certified/open-liberty-operator.v0.7.0.clusterserviceversion.yaml
deploy/olm-catalog/open-liberty-operator-community/0.7.0/open-liberty-operator.v0.7.0.clusterserviceversion.yaml

This PR adds an annotation to the CSV that will be detected and used by App Navigator to automatically produce menu items and dialogs in the App Nav UI for submitting day 2 operations - currently trace and dump.
This PR does not produce a user facing change to for the OLM catalog UI or any API, so no OpenLiberty operator doc changes are needed.
Fixes # Issue to be created...

Add day2 operations annotation to CSV

---

deploy/dashboards/logging/README.md

Clarify that when` jsonAccessLogFields="logFormat"` we need to specify the default tokens that are needed in the logFormat attribute to make our dashboards work.

Add README.md in our logging dashboards

---

doc/observability-deployment-rhocp4.2-4.4.adoc

Main Changes to Doc:
- Updating note to mention that this doc was tested with RHOCP 4.5
- Switching Kabanero Logging/Monitoring guide links to IBMKC ICP4A docs, since they will be the most up to date guides from now on
- Updating mpHealth example to latest version (2.2)

Updating Open Liberty Observability Doc for RHOCP 4.5

---

deploy/dashboards/metrics/RHOCP4.3-GrafanaOperator3.0.2-Grafana5.2/open-liberty-grafana-mpMetrics1.x.yml
deploy/dashboards/metrics/RHOCP4.3-GrafanaOperator3.0.2-Grafana5.2/open-liberty-grafana-mpMetrics2.x.yml

This PR is needed because when Thanos is used as a data source, the Grafana dashboards does not work. The pod query adds the prometheus server where the data comes from which results to the value of the pod variable being incorrect.
e.g.
Thanos current pod value:  `mydemoapp-7575584657-6c9vl",prometheus="openshift-user-workload-monitoring/user-workload `
Filtered out prometheus for pod value:  `mydemoapp-7575584657-6c9vl `
Fixes #190

Update query for pod variable in grafana dashboards

---

bundle/tests/scorecard/kuttl/annotations/00-assert.yaml
bundle/tests/scorecard/kuttl/annotations/01-assert.yaml
bundle/tests/scorecard/kuttl/image-stream/01-assert.yaml
bundle/tests/scorecard/kuttl/image-stream/02-assert.yaml
bundle/tests/scorecard/kuttl/image-stream/03-assert.yaml
bundle/tests/scorecard/kuttl/image-stream/04-assert.yaml
bundle/tests/scorecard/kuttl/probe/00-assert.yaml
bundle/tests/scorecard/kuttl/probe/01-assert.yaml
bundle/tests/scorecard/kuttl/probe/02-errors.yaml
bundle/tests/scorecard/kuttl/pullpolicy/00-assert.yaml
bundle/tests/scorecard/kuttl/pullpolicy/01-assert.yaml
bundle/tests/scorecard/kuttl/pullpolicy/02-assert.yaml
bundle/tests/scorecard/kuttl/pullpolicy/03-assert.yaml
bundle/tests/scorecard/kuttl/sso1-social/01-assert.yaml
bundle/tests/scorecard/kuttl/sso1-social/02-assert.yaml
bundle/tests/scorecard/kuttl/sso1-social/03-assert.yaml
bundle/tests/scorecard/kuttl/sso2-providers/01-assert.yaml
bundle/tests/scorecard/kuttl/sso2-providers/02-assert.yaml

This ensure that the pods being asserted on are from
the current test

Check pods labels during kuttl tests

---

Makefile

- Similar to [RCO](https://github.com/application-stacks/runtime-component-operator/blob/2b442929246c2a4fc4c2b546b888f3d3252d2f2e/Makefile#L137), install operator-sdk before bundle
Fixes #

Install operator-sdk before bundle

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manifests/kustomization.yaml
config/manifests/serviceBindingPatch.yaml

This allows the service binding secret to be displayed in the OpenShift UI.
The description annotations need to be added as a kustomize patch,
as the secret field isn't specified in types.go, so annotations can't be added there.

 Add kustomization patch to add description for service binding secret

---

bundle/tests/scorecard/kuttl/dump/00-assert.yaml
bundle/tests/scorecard/kuttl/dump/00-liberty.yaml
bundle/tests/scorecard/kuttl/dump/01-dump.yaml
bundle/tests/scorecard/kuttl/trace/00-assert.yaml
bundle/tests/scorecard/kuttl/trace/00-liberty.yaml
bundle/tests/scorecard/kuttl/trace/01-assert.yaml
bundle/tests/scorecard/kuttl/trace/01-trace.yaml
bundle/tests/scorecard/kuttl/trace/02-assert.yaml
bundle/tests/scorecard/kuttl/trace/02-change-pod.yaml
bundle/tests/scorecard/kuttl/trace/03-assert.yaml
bundle/tests/scorecard/kuttl/trace/03-trace-disable.yaml
bundle/tests/scorecard/kuttl/trace/04-delete-app.yaml

- Fixes an issue where if the Trace or Dump kuttl tests are run before Basic, Basic will fail due to leftover resources

Fix for intermittent kuttl test issue

---

controllers/openlibertyapplication_controller.go

- Allows the image name to have multiple /'s
Fixes #326

Fix for multiple /'s in application image name

---

controllers/openlibertyapplication_controller.go
go.mod
go.sum
vendor/github.com/application-stacks/runtime-component-operator/api/v1beta2/runtimecomponent_types.go
vendor/github.com/application-stacks/runtime-component-operator/api/v1beta2/zz_generated.deepcopy.go
vendor/github.com/application-stacks/runtime-component-operator/utils/utils.go
vendor/modules.txt

- Adding https://github.com/application-stacks/runtime-component-operator/pull/293 and https://github.com/application-stacks/runtime-component-operator/pull/343 to 0.8.x for OLO v0.8.1  
Fixes #328

Adding RCO PR 293 and 343 to 0.8.x for OLO v0.8.1

---

Makefile

- Changes the createdAt format to yyyy-mm-ddTTimeZ for better rendering in OperatorHub UI

Change createdAt date format for better rendering in UI

---

Dockerfile

Removes the symbol table which saves aprox 10mb from the image
This means attaching a debugger won't be useful, but that is
unlikely to be useful.
This is also recommended by the cloudpak playbook

Strip the manager binary

---

.travis.yml

- E2E testing on Minikube is failing with unknown reason and blocking builds. Temporarily skip the testing until fix is in.
Related: https://github.com/OpenLiberty/open-liberty-operator/issues/335

Disable e2e testing on Minikube temporarily

---

Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
scripts/update-sample.sh

The RedHat certification requires that images are referenced by sha. Add a sha for the sample image, and also add a script to update the sha when 'make bundle' is run
This is the OLO portion of WASdev/websphere-liberty-operator#214

Use image sha for sample image

---

ebcDockerBuilderOLO.jenkinsfile
scripts/pipeline/request-ciorchestrator.sh

CI Orchestrator doesn't support GitHub tags. It only supports branches. Use the following workaround suggested by the CI Orchestrator team: checkout the tag so that the orchestrator can build images on Jenkins
Similar to WLO PRs https://github.com/WASdev/websphere-liberty-operator/pull/444 and https://github.com/WASdev/websphere-liberty-operator/pull/436
Fixes #

Build images with GitHub tags

---

controllers/openlibertyapplication_controller.go

- Delete NetworkPolicy when switching to Knative
PR for https://github.com/application-stacks/runtime-component-operator/issues/500
Fixes #

Clean up NetworkPolicy when switching to Knative

---

controllers/openlibertyapplication_controller.go
go.mod
go.sum

- Set the security context on Knative Service (user specified or the default - the default matches what's set by Knative itself otherwise)
- Knative changed the label used to control visibility of route (adding the new label for now, we could remove the old label in the future if it's 100% not needed) - PR for https://github.com/application-stacks/runtime-component-operator/issues/515
- Always use utils method to create controller configmap (fix for https://github.com/application-stacks/runtime-component-operator/issues/506)
Fixes #

Update RCO module to include knative and operator configmap label updates

---

scripts/pipeline/request-ciorchestrator.sh

- Set ecosystemRouting to prod in ciorchestrator req - similar to WLO and also suggested by Chris Webster([here](https://ibm-cloud.slack.com/archives/C31GDF6CD/p1682335003231549?thread_ts=1680723628.432789&cid=C31GDF6CD))
- 
Fixes #

Set ecosystemRouting to prod in ciorchestrator req

---

Makefile
config/kustomize/operator/kustomization.yaml
config/kustomize/roles/kustomization.yaml
internal/deploy/kustomize/1.2.0/README.adoc
internal/deploy/kustomize/1.2.0/base/kustomization.yaml
internal/deploy/kustomize/1.2.0/base/open-liberty-operator.yaml
internal/deploy/kustomize/1.2.0/base/open-liberty-roles.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-all-namespaces/cluster-roles.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-all-namespaces/kustomization.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-all-namespaces/olo-all-namespaces.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-ns/olo-deployment.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-ns/olo-roles.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-ns/olo-sa.yaml
internal/deploy/kustomize/daily/README.adoc
internal/deploy/kustomize/daily/base/kustomization.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-roles.yaml
internal/deploy/kustomize/daily/overlays/watch-all-namespaces/cluster-roles.yaml
internal/deploy/kustomize/daily/overlays/watch-all-namespaces/kustomization.yaml
internal/deploy/kustomize/daily/overlays/watch-all-namespaces/olo-all-namespaces.yaml
internal/deploy/kustomize/daily/overlays/watch-another-namespace/olo-ns/olo-deployment.yaml
internal/deploy/kustomize/daily/overlays/watch-another-namespace/olo-ns/olo-roles.yaml
internal/deploy/kustomize/daily/overlays/watch-another-namespace/olo-ns/olo-sa.yaml

- Avoid using default namespace, which throws permission errors
- Fix watch-all-namespaces
- Align with WebSphere Liberty doc
Issue: https://github.com/OpenLiberty/open-liberty-operator/issues/415

Replace default namespace to open-liberty for kustomize artifacts

---

bundle/tests/scorecard/kuttl/probe/03-assert.yaml
bundle/tests/scorecard/kuttl/probe/03-probe-defaults.yaml
bundle/tests/scorecard/kuttl/probe/04-assert.yaml
bundle/tests/scorecard/kuttl/probe/05-assert.yaml
bundle/tests/scorecard/kuttl/storage/03-assert.yaml
bundle/tests/scorecard/kuttl/storage/05-assert.yaml

- Reverted changes make to kuttl e2e tests now that the getting started app is multiarch
- Updated storage tests now that it uses onepipeline

Kuttl test changes for multiarch

---

.one-pipeline-cd.yaml
.one-pipeline.yaml

- skopeo started returning multiple sha values when using `| grep Digest | grep -o 'sha[^\"]*'` to filter the results.
Replaced with `| jq '.Digest'| sed -e 's/"//g'` to ensure only the digest is returned

Update skopeo command to return single digest

---

scripts/setup-kind-cluster.sh

This issue was discovered as part of the investigations into 
WASdev/websphere-liberty-operator#316
https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files
It may (or may not) be contributing to test failures

fix 'too many open files' issue in kind

---

.github/ISSUE_TEMPLATE/bug_report.md

Removed references to appsody from bug template
Appsody is dead so the bug template doesn't need to ask information about it.

Remove Appsody from bug template

---

bundle/tests/scorecard/kuttl/monitor/02-assert.yaml
bundle/tests/scorecard/kuttl/monitor/02-update-monitor.yaml

The clusters used for kind testing use a newer version of Prometheus which insist on the scheme name being either HTTPS or HTTP, so this test fails there.

Get monitoring test to work on kind

---

bundle/tests/scorecard/kuttl/monitor/02-assert.yaml
bundle/tests/scorecard/kuttl/monitor/02-update-monitor.yaml
go.mod
go.sum

Prometheus has added validation which checks that the scheme is either 'https' or 'http' (lowercase only)

Latest version of utils from RCO to pick up prometeus fix

---

Dockerfile
Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
bundle/tests/scorecard/kuttl/basic/00-assert.yaml
bundle/tests/scorecard/kuttl/dump/01-assert.yaml
bundle/tests/scorecard/kuttl/trace/01-assert.yaml
config/manager/manager.yaml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
ebcDockerBuilderOLO.jenkinsfile
index.Dockerfile
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml
scripts/installers/install-opm.sh
scripts/update-sample.sh
utils/utils.go

- Update the OLO version to 1.2.1
- Update the catalog base image (to resolve CVEs) and OPM version to 4.12. OCP 4.10 is supported till September 2023, so left the OC CLI version at 4.10 for now.
- Update sample app
Fixes #

Update OLO version to 1.2.1 and update catalog base image and OPM versions

---

.one-pipeline.yaml

- Introduce a SKIP_SCANS environment variable to the onepipeline builds to reduce the time it takes to run a build if we are just looking at the test.

Enable a tests only build in onepipeline

---

Makefile
config/kustomize/watch-all/kustomization.yaml
config/kustomize/watch-all/patches/delete-service-account.yaml
config/kustomize/watch-another/kustomization.yaml
config/kustomize/watch-another/patches/delete-service-account.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml
internal/deploy/kustomize/daily/overlays/watch-all-namespaces/cluster-roles.yaml
internal/deploy/kustomize/daily/overlays/watch-another-namespace/olo-watched-ns/watched-roles.yaml

- Adds in auto generation for kustomize artifacts
- Updates the current artifacts with the output from the generator
Related [websphere-liberty-operator/issues/446](https://github.com/WASdev/websphere-liberty-operator/issues/446)

Added auto generation for kustomize artifacts

---

controllers/openlibertyapplication_controller.go

The previous change to deprecate .spec.ServiceAccountName was not reflected in the controller where the default service account is created. Use the new utils method to check if a service account has been specified before creating the default account
This change was missed from the initial fix for
https://github.com/OpenLiberty/open-liberty-operator/issues/462

Bug fix: create default service account if name not specified

---

Dockerfile
Makefile

This removes a dependency on dockerhub
To deal with dockerhub rate limits
See https://github.com/WASdev/websphere-liberty-operator/issues/270

Use ubi instead of golang to build the manager

---

go.mod
go.sum

Pick up fix from RCO to filter out knative annotations from the knative service, as this causes a knative error
OLO fix for #474

RCO utils update to filter knative annotations

---

controllers/semeru_compiler.go

Enable Semeru Cloud Compiler for InstantOn

---

Makefile

As the go-version env var is not available in the z and p build environment

Add go version to build-operator-pipeline target

---

go.mod
go.sum

Pick up the fix to properly read the operator configmap when watching another namespace
OLO fix for https://github.com/application-stacks/runtime-component-operator/issues/590

Update to latest RCO - pick up config map fix

---

controllers/ltpa_keys_sharing.go
utils/utils.go

Relating to https://github.com/WASdev/websphere-liberty-operator/issues/568. This change covers the scenario when the LTPA Job config is outdated (i.e. pull secret ref or service account ref has changed) just before the LTPA Secret is created. In this case, the operator could potentially be waiting on an LTPA Job that might fail. Instead, the operator will react to this and restart LTPA generation once again matching the olapp spec (pullsecret/service account/etc.), lowering the risk of waiting on a failed Job.

Set LTPA Job to match olapp leader's config

---

utils/utils.go

LTPA Manager to use `.status.imageReference` instead of `.spec.applicationImage` when passing applicationImage over to the LTPA Job.

Use imageReference over applicationImage in LTPA Job

---

config/rbac/kind-kuttl-rbac.yaml
config/rbac/kuttl-rbac.yaml

Add RBAC perms for LTPA tests
- Kuttl needs ability to get, list, patch and delete the Job resource covering the `ltpa` and `ltpa-outdated-job` tests

Add RBAC perms for LTPA tests

---

go.mod
go.sum

Specifically the fix to allow prevention of automounting the service account token into knative services
This addresses issue #505

Grab latest RCO

---

doc/observability-deployment.adoc
doc/openshift-logging-rhocp_4.7+.adoc
doc/openshift-monitoring.adoc

**Description of changes:**
Logging Guide:
The OCP guides removed mention of installing the OpenShift Elasticsearch Operator, since they now provide two log store options: the OpenShift Elasticsearch Operator and the Loki Operator (so it's up to the user to choose). However, the cluster logging instance deployed later uses Elasticsearch as its log store, so for simplicity, I just added an instruction to install the Elasticsearch Operator as well.
To consider: The guide also says that the Elasticsearch Operator is now deprecated, and that we should look to using Loki/Vector as the future option instead.
Monitoring Guide:
The Grafana Operator's CRs and apiVersion have been renamed, so a direct copy paste of the yaml from the blog won't work for deploying the Grafana datasource CR. I've …

Update Observability guides for OCP 4.15

---

controllers/openlibertyapplication_controller.go

- Prevents the ServiceAccount from being deleted or managed when a user specifies a `.spec.serviceAccountName` that matches the name of the `OpenLibertyApplication`.
- PR for https://github.com/OpenLiberty/open-liberty-operator/issues/433
<!--
Automatically closes the linked issue when PR is merged.
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
PR for #433 issue

Prevent deleting/managing a CR-specified ServiceAccount matching the default

---

go.mod
go.sum

Fix picked up from latest version of RCO
To deal with issue
https://github.com/WASdev/websphere-liberty-operator/issues/655

Don't create certs with common name longer than 64

---

doc/observability-deployment.adoc
doc/openshift-logging-rhocp_4.7+.adoc
doc/openshift-monitoring.adoc

Updating the Observability docs for 4.16.
Mainly version testing updates and link updates.
The switch from using the EFK stack to Loki/Vector/OCP console visualizations will be addressed in a different issue, since the solution is more involved.

Update Observability docs for 4.16

---

api/v1/openlibertyapplication_types.go

For issue https://github.com/OpenLiberty/open-liberty-operator/issues/516
- Adds BaseComponentDNS
- Implements RuntimeComponentDNS at `.spec.dns` with attributes 
- `.spec.dns.policy` (`corev1.DNSPolicy`)
- `.spec.dns.config` (`corev1.PodDNSConfig`)
Fixes #

Add support for Pod DNS policy and config

---

internal/controller/assets/create_ltpa_keys.sh

- Set LTPA password to 15 characters to resolve problem of securityUtility throwing FFDC due to padding issues
Fixes https://github.com/OpenLiberty/open-liberty-operator/issues/620

Revert LTPA password length to 15 characters

---

doc/observability-deployment.adoc

This adds info about liveness/readiness pods to the the mpHealth 3.1+ section.
no
fixes: https://github.ibm.com/websphere/WS-CD-Open/issues/33119

add liveness and readiness probes info to mphealth 3.1+

---

cmd/main.go
go.mod
go.sum
internal/controller/openlibertyapplication_controller.go

Part of #638
Picks up latest RCO for log level framework, and moves 'semeru start' log messages to debug level

Add logging levels to reduce default log output

---

go.mod
go.sum

- Updating Error RCO for `Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference`
Fixes #

Add Reconcile Interval check

---

internal/controller/ltpa_keys_sharing.go
utils/utils.go

- Adds a consistent labelling `app.kubernetes.io/name: olo-managed-ltpa-config-generation` and `app.kubernetes.io/name: olo-managed-ltpa-generation` to the LTPA config and key Jobs, respectively.
Fixes #

Add consistent label to LTPA Jobs

---

doc/user-guide-v1.adoc
internal/controller/openlibertyapplication_controller.go

- Resolves https://github.com/OpenLiberty/open-liberty-operator/issues/668
- avoids confusion when switching between custom and operator-created service accounts
- mention that the operator-created service account is dynamically updated (i.e. checks .spec.pullSecret)
- mention that the user-provided service account will be treated as read-only
Fixes #

Document .spec.serviceAccount.name limitations

---

api/v1/openlibertyperformancedata_types.go
internal/controller/assets/helper/linperf.sh
internal/controller/openlibertyperformancedata_controller.go
internal/controller/openlibertytrace_controller.go
utils/socket/linperf.go
utils/socket/linperf_test.go
utils/utils.go

Fixes https://github.com/OpenLiberty/open-liberty-operator/issues/759
- Uses `$WLP_OUTPUT_DIR/helper` instead of `/output/helper` for copying `linperf.sh` into the pod
- Outputs error message when required `linperf.sh` packages are not installed in the Liberty container OS
- Outputs error message when `/serviceability` mount could not be found in the Liberty container
- Stops frequently using lastUpdatedTime and sets lastTransitionTime occasionally instead.
- Fixes issue with performance data file name not being parsed for long file paths
- Sets trace output dir from the `/serviceability/ns/pod` to the `/serviceability/ns/pod/logs` folder.
Fixes #

Add error messages to performance data feature 
