OpenLiberty/open-liberty-operator

deploy/operator_rbac.yaml
olm/open-liberty-0.0.1.clusterserviceversion.yaml

Need to let the operator create service accounts, roles and role bindings.

Added permissions to let the operator create RBAC artifacts

---

olm/open-liberty-crd.yaml

I added openAPIV3Schema validation logic into the olm/open-liberty-crd.yaml.   I added a couple of comments within this new validation that are questions on whether this is good for now or ???
I plan on removing those comments before merging.

Add validation to crd

---

olm/open-liberty-0.0.1.clusterserviceversion.yaml

Made some changes to honor the requirements here:
https://github.com/operator-framework/community-operators/blob/master/docs/required-fields.md

Change invalid required fields in the CSV

---

olm/open-liberty-0.0.1.clusterserviceversion.yaml
olm/open-liberty-crd.yaml

issue 21 -- add crd validation for cpu and memory

---

olm/open-liberty-0.0.1.clusterserviceversion.yaml

Add resources to resources section in CSV:CRD

---

olm/open-liberty-0.0.1.clusterserviceversion.yaml

Add maturity: beta   to CSV so  operator-courier verify   passes.
Choices for maturity are here https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md

Add maturity to CSV

---

olm/open-liberty-0.0.1.clusterserviceversion.yaml

Change maturity

---

docs/observability-deployment.md

authors: David Chan, Prashanth Gunapalasingam
Makes references to dashboards to be merged from the following PRs:
#36 
#37

Initial drop of Observability document

---

Makefile
deploy/releases/daily/openliberty-app-cluster-rbac.yaml

Update Makefile to be similar to that of Appsody operator

---

deploy/crds/openliberty.io_openlibertydumps_cr.yaml
deploy/releases/daily/openliberty-app-cluster-rbac.yaml
deploy/releases/daily/openliberty-app-operator.yaml
deploy/role.yaml

- Add pods/exec to role and cluster role
- Fix dump CR
Fixes #

Add pods/exec to role and cluster role

---

pkg/apis/openliberty/v1beta1/openlibertyapplication_types.go

- Initializes consume/provides fields
**Does this PR introduce a user-facing change?** N/A

Initialize missing values for service binding

---

README.md
doc/user-guide.md

- Documentation for serviceability config and trace operation
No

Documentation for serviceability config and trace operation

---

deploy/crds/openliberty.io_openlibertyapplications_cr.yaml
deploy/crds/openliberty.io_openlibertyapplications_crd.yaml
deploy/crds/openliberty.io_openlibertydumps_cr.yaml
deploy/crds/openliberty.io_openlibertydumps_crd.yaml
deploy/crds/openliberty.io_openlibertytraces_cr.yaml
deploy/crds/openliberty.io_openlibertytraces_crd.yaml
deploy/releases/daily/openliberty-app-crd.yaml
pkg/apis/openliberty/v1beta1/openlibertyapplication_types.go
pkg/apis/openliberty/v1beta1/openlibertydump_types.go
pkg/apis/openliberty/v1beta1/openlibertytrace_types.go
pkg/apis/openliberty/v1beta1/operations.go
pkg/controller/openlibertydump/openlibertydump_controller.go
pkg/controller/openlibertytrace/openlibertytrace_controller.go
pkg/utils/utils.go

- Add multiple shortnames
- Improve error handling
- Record events
- Display failure reason and message
- Minor updates

Improve error handling + record events

---

doc/user-guide.md

- Fix issue #126 (The parameters table in "Configuration" section of "user-guide.md" is not well formatted)
- No
Fixes #126

Fix issue #126: Remove redundant empty line

---

deploy/olm-catalog/open-liberty-operator-certified/open-liberty-operator.v0.4.0.clusterserviceversion.yaml
deploy/olm-catalog/open-liberty-operator-community/0.4.0/open-liberty-operator.v0.4.0.clusterserviceversion.yaml

Signed-off-by: leochr <leojc@ca.ibm.com>
- update description in CSV

Update CSV descriptions

---

deploy/releases/0.4.0/readme.md
doc/troubleshooting.md
doc/user-guide.md

Signed-off-by: leochr <leojc@ca.ibm.com>
- documentation and troubleshooting for SSO

Documentation and troubleshooting for Single Sign-on

---

cmd/manager/main.go
pkg/utils/utils.go
version/version.go

Signed-off-by: leochr <leojc@ca.ibm.com>
- Add version.go & print version
- Add env variable to force deployment to update pods when value from SSO secret is updated
Fixes #

Add version + sso secret env variable

---

deploy/releases/0.5.0/readme.md

Signed-off-by: leochr <leojc@ca.ibm.com>
- Minor update to readme

Minor update to readme

---

doc/observability-deployment-rhocp4.2-4.4.adoc

The PR is needed to help further clarify our observability doc.
Fixes #200

Update observability.doc to address clarifications

---

CHANGELOG.md
build/Dockerfile
deploy/cluster_role.yaml
deploy/releases/0.7.1/openliberty-app-cluster-rbac.yaml
deploy/releases/0.7.1/openliberty-app-crd.yaml
deploy/releases/0.7.1/openliberty-app-operator.yaml
deploy/releases/0.7.1/readme.adoc
version/version.go

Changes for 0.7.1 release

---

api/v1beta1/openlibertytrace_types.go
controllers/openlibertytrace_controller.go

Ensure disable = false always present in OpenLibertyTrace

---

bundle/tests/scorecard/kuttl/knative/00-errors.yaml
bundle/tests/scorecard/kuttl/knative/00-runtime-no-knative.yaml
bundle/tests/scorecard/kuttl/knative2/00-runtime-knative.yaml
bundle/tests/scorecard/kuttl/knative2/01-runtime-remove-knative.yaml

Quick fix for the knative kuttl test

Fix knative kuttl test

---

.travis.yml
Makefile
config/manager/manager.yaml
config/rbac/kuttl-rbac.yaml
config/scorecard/patches/olm.config.yaml
scripts/build-manifest.sh
scripts/build-releases.sh
scripts/e2e.sh
scripts/installers/install-operator-sdk.sh

- Enable E2E tests for OLO
Fixes #260

Enable e2e tests

---

.travis.yml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
controllers/openlibertyapplication_controller.go
main.go
utils/utils.go
utils/utils_test.go

- Update leader lease
- update pods when certs are refreshed
- disable multi-arch builds temporarily (due to Travis infrastructure issue)
Fixes #

Update leader lease, update pods when certs are refreshed

---

bundle/tests/scorecard/kuttl/affinity/00-assert.yaml
bundle/tests/scorecard/kuttl/affinity/00-errors.yaml
bundle/tests/scorecard/kuttl/affinity/00-node-no-affinity.yaml
bundle/tests/scorecard/kuttl/affinity/01-assert.yaml
bundle/tests/scorecard/kuttl/affinity/01-node-affinity.yaml
bundle/tests/scorecard/kuttl/affinity/02-assert.yaml
bundle/tests/scorecard/kuttl/affinity/02-pod-affinity.yaml
bundle/tests/scorecard/kuttl/affinity/03-assert.yaml
bundle/tests/scorecard/kuttl/affinity/03-pod-antiaffinity.yaml
bundle/tests/scorecard/kuttl/affinity/04-assert.yaml
bundle/tests/scorecard/kuttl/affinity/04-node-affinity.yaml
bundle/tests/scorecard/kuttl/affinity/05-assert.yaml
bundle/tests/scorecard/kuttl/affinity/05-errors.yaml
bundle/tests/scorecard/kuttl/affinity/05-no-node-affinity.yaml
bundle/tests/scorecard/kuttl/affinity/06-affinity-architecture.yaml
bundle/tests/scorecard/kuttl/affinity/06-assert.yaml
bundle/tests/scorecard/kuttl/affinity/07-delete.yaml
bundle/tests/scorecard/kuttl/affinity/README.txt

- Adds the Affinity kuttl tests to OLO

Add Affinity kuttl tests

---

deploy/dashboards/logging/README.md

Adding a change to the README.md to indicate which dashboards to use when on AppNav.

Add instructions for AppNav users

---

deploy/kustomize/daily/README.adoc
deploy/kustomize/daily/base/kustomization.yaml
deploy/kustomize/daily/base/open-liberty-operator-crd.yaml
deploy/kustomize/daily/base/open-liberty-operator-deployment.yaml
deploy/kustomize/daily/examples/watch-all-namespaces/kustomization.yaml
deploy/kustomize/daily/examples/watch-all-namespaces/olo-ns.yaml
deploy/kustomize/daily/examples/watch-another-namespace/kustomization.yaml
deploy/kustomize/daily/examples/watch-another-namespace/olo-deployment.yaml
deploy/kustomize/daily/examples/watch-another-namespace/olo-roles.yaml
deploy/kustomize/daily/examples/watch-another-namespace/olo-sa.yaml
deploy/kustomize/daily/examples/watch-another-namespace/watched-roles.yaml
deploy/kustomize/daily/examples/watch-own-namespace/kustomization.yaml
deploy/kustomize/daily/overlays/watch-all-namespaces/cluster-roles.yaml
deploy/kustomize/daily/overlays/watch-all-namespaces/kustomization.yaml
deploy/kustomize/daily/overlays/watch-all-namespaces/olo-all-namespaces.yaml
deploy/kustomize/daily/overlays/watch-another-namespace/kustomization.yaml
deploy/kustomize/daily/overlays/watch-another-namespace/olo-deployment.yaml
deploy/kustomize/daily/overlays/watch-another-namespace/olo-roles.yaml
deploy/kustomize/daily/overlays/watch-another-namespace/olo-sa.yaml
deploy/kustomize/daily/overlays/watch-another-namespace/watched-roles.yaml

on any Kubernetes, along with examples of how to modify
the installation

Add kustomize files to allow the operator to be installed

---

deploy/releases/0.8.0/kubectl/openliberty-app-crd.yaml
deploy/releases/0.8.0/kubectl/openliberty-app-operator.yaml
deploy/releases/0.8.0/kubectl/openliberty-app-rbac-watch-all.yaml
deploy/releases/0.8.0/kubectl/openliberty-app-rbac-watch-another.yaml
deploy/releases/0.8.0/kubectl/readme.adoc
deploy/releases/0.8.0/readme.adoc

- Add instructions for installing with kubectl for 0.8.0
https://github.com/application-stacks/runtime-component-operator/issues/246

0.8.0 doc update: kubectl

---

bundle/tests/scorecard/kuttl/sso1-social/03-liberty-nosso.yaml
bundle/tests/scorecard/kuttl/storage/01-liberty-no-storage.yaml

- pullSecret is preventing Deployment to be created. Removing pullSecret since the tests do not require pullSecret.
Fixes #

Remove pullSecret in kuttl tests

---

deploy/releases/0.8.1/readme.adoc

- The operator is not yet available from the Red Hat's Certified Operators Catalog.
Fixes #

Update readme of 0.8.1

---

deploy/releases/0.8.1/readme.adoc

- Include the Operator Hub install option.
Fixes #

Update 0.8.1 release document

---

.travis.yml
Dockerfile
Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
bundle/tests/scorecard/kuttl/auto3/01-add-scaling.yaml
bundle/tests/scorecard/minikube-kuttl/ingress-certificate/00-assert.yaml
bundle/tests/scorecard/minikube-kuttl/ingress-certificate/00-secret.yaml
bundle/tests/scorecard/minikube-kuttl/ingress-certificate/01-assert.yaml
bundle/tests/scorecard/minikube-kuttl/ingress-certificate/01-ol-with-cert.yaml
bundle/tests/scorecard/minikube-kuttl/ingress-certificate/02-assert.yaml
bundle/tests/scorecard/minikube-kuttl/ingress-certificate/02-delete-ingress.yaml
bundle/tests/scorecard/minikube-kuttl/ingress-certificate/02-errors.yaml
bundle/tests/scorecard/minikube-kuttl/ingress-certificate/03-delete-secret.yaml
bundle/tests/scorecard/minikube-kuttl/ingress/00-assert.yaml
bundle/tests/scorecard/minikube-kuttl/ingress/00-ingress.yaml
bundle/tests/scorecard/minikube-kuttl/ingress/01-assert.yaml
bundle/tests/scorecard/minikube-kuttl/ingress/01-delete-ingress.yaml
bundle/tests/scorecard/minikube-kuttl/ingress/01-errors.yaml
config/manager/manager.yaml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
config/rbac/minikube-kuttl-rbac.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
deploy/kustomize/daily/base/open-liberty-operator.yaml
go.mod
go.sum
scripts/e2e-minikube.sh
scripts/installers/install-minikube.sh
vendor/github.com/application-stacks/runtime-component-operator/utils/utils.go
vendor/modules.txt

Updates for 0.8.2. release of 0.8.x branch

---

bundle/tests/scorecard/kuttl/init-deployment/00-assert.yaml
bundle/tests/scorecard/kuttl/init-deployment/00-liberty-basic.yaml
bundle/tests/scorecard/kuttl/init-deployment/01-add-init-container.yaml
bundle/tests/scorecard/kuttl/init-deployment/01-assert.yaml
bundle/tests/scorecard/kuttl/init-deployment/02-assert.yaml
bundle/tests/scorecard/kuttl/init-deployment/02-errors.yaml
bundle/tests/scorecard/kuttl/init-deployment/02-rm-init-container.yaml
bundle/tests/scorecard/kuttl/init-stateful/00-assert.yaml
bundle/tests/scorecard/kuttl/init-stateful/00-liberty-basic.yaml
bundle/tests/scorecard/kuttl/init-stateful/01-add-init-container.yaml
bundle/tests/scorecard/kuttl/init-stateful/01-assert.yaml
bundle/tests/scorecard/kuttl/init-stateful/02-assert.yaml
bundle/tests/scorecard/kuttl/init-stateful/02-errors.yaml
bundle/tests/scorecard/kuttl/init-stateful/02-rm-init-container.yaml
bundle/tests/scorecard/kuttl/sidecar-deployment/00-assert.yaml
bundle/tests/scorecard/kuttl/sidecar-deployment/00-liberty-basic.yaml
bundle/tests/scorecard/kuttl/sidecar-deployment/01-add-sidecar.yaml
bundle/tests/scorecard/kuttl/sidecar-deployment/01-assert.yaml
bundle/tests/scorecard/kuttl/sidecar-deployment/02-assert.yaml
bundle/tests/scorecard/kuttl/sidecar-deployment/02-errors.yaml
bundle/tests/scorecard/kuttl/sidecar-deployment/02-remove-sidecar.yaml
bundle/tests/scorecard/kuttl/sidecar-stateful/00-assert.yaml
bundle/tests/scorecard/kuttl/sidecar-stateful/00-liberty-basic.yaml
bundle/tests/scorecard/kuttl/sidecar-stateful/01-add-sidecar.yaml
bundle/tests/scorecard/kuttl/sidecar-stateful/01-assert.yaml
bundle/tests/scorecard/kuttl/sidecar-stateful/02-assert.yaml
bundle/tests/scorecard/kuttl/sidecar-stateful/02-errors.yaml
bundle/tests/scorecard/kuttl/sidecar-stateful/02-remove-sidecar.yaml

This addresses issue application-stacks/runtime-component-operator#305

Add tests for sidecar and init containers

---

CHANGELOG.md

Update change log for 0.8.2

---

deploy/releases/0.8.2/kubectl/openliberty-app-crd.yaml
deploy/releases/0.8.2/kubectl/openliberty-app-operator.yaml
deploy/releases/0.8.2/kubectl/openliberty-app-rbac-watch-all.yaml
deploy/releases/0.8.2/kubectl/openliberty-app-rbac-watch-another.yaml
deploy/releases/0.8.2/kubectl/readme.adoc
deploy/releases/0.8.2/kustomize/README.adoc
deploy/releases/0.8.2/kustomize/base/kustomization.yaml
deploy/releases/0.8.2/kustomize/base/open-liberty-crd.yaml
deploy/releases/0.8.2/kustomize/base/open-liberty-operator.yaml
deploy/releases/0.8.2/kustomize/examples/watch-all-namespaces/kustomization.yaml
deploy/releases/0.8.2/kustomize/examples/watch-all-namespaces/olo-ns.yaml
deploy/releases/0.8.2/kustomize/examples/watch-another-namespace/kustomization.yaml
deploy/releases/0.8.2/kustomize/examples/watch-another-namespace/olo-deployment.yaml
deploy/releases/0.8.2/kustomize/examples/watch-another-namespace/olo-roles.yaml
deploy/releases/0.8.2/kustomize/examples/watch-another-namespace/olo-sa.yaml
deploy/releases/0.8.2/kustomize/examples/watch-another-namespace/watched-roles.yaml
deploy/releases/0.8.2/kustomize/examples/watch-own-namespace/kustomization.yaml
deploy/releases/0.8.2/kustomize/overlays/watch-all-namespaces/cluster-roles.yaml
deploy/releases/0.8.2/kustomize/overlays/watch-all-namespaces/kustomization.yaml
deploy/releases/0.8.2/kustomize/overlays/watch-all-namespaces/olo-all-namespaces.yaml
deploy/releases/0.8.2/kustomize/overlays/watch-another-namespace/kustomization.yaml
deploy/releases/0.8.2/kustomize/overlays/watch-another-namespace/olo-deployment.yaml
deploy/releases/0.8.2/kustomize/overlays/watch-another-namespace/olo-roles.yaml
deploy/releases/0.8.2/kustomize/overlays/watch-another-namespace/olo-sa.yaml
deploy/releases/0.8.2/kustomize/overlays/watch-another-namespace/watched-roles.yaml
deploy/releases/0.8.2/readme.adoc

Add kubectl/kustomize install files for 0.8.2 release

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml

As per issue application-stacks/runtime-component-operator#415
Already done for the 0.8.x branch via issue #352

Change sample app to the open liberty getting started

---

.whitesource

Enables Mend scanning
- 
- 
No
N/A

Enable mend

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
deploy/kustomize/daily/base/open-liberty-operator.yaml
main.go

https://github.com/application-stacks/runtime-component-operator/issues/437
Fixes # https://github.com/application-stacks/runtime-component-operator/issues/437

Add readiness and liveness probes

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manifests/kustomization.yaml
config/manifests/probesPatch.yaml
config/manifests/securityContextPatch.yaml

Add patches for securityContext and Probes

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml

- expose the sample app and set replicas to 1
- 
Fixes #

update sample CR

---

bundle/tests/scorecard/kuttl/manage-tls/00-certmanager-with-manage-tls.yaml
bundle/tests/scorecard/kuttl/manage-tls/01-certmanager-without-manage-tls.yaml
bundle/tests/scorecard/kuttl/manage-tls/02-certmanager-statefulset-with-manage-tls.yaml
bundle/tests/scorecard/kuttl/manage-tls/03-service-ca-statefulset-with-manage-tls.yaml
bundle/tests/scorecard/kuttl/manage-tls/05-service-ca-with-manage-tls.yaml
bundle/tests/scorecard/kuttl/manage-tls/06-service-ca-without-manage-tls.yaml
bundle/tests/scorecard/kuttl/manage-tls/08-byo-with-manage-tls.yaml
bundle/tests/scorecard/kuttl/security-context/00-default.yaml
bundle/tests/scorecard/kuttl/security-context/01-override.yaml
bundle/tests/scorecard/kuttl/security-context/02-privileged-override.yaml
bundle/tests/scorecard/kuttl/security-context/03-capabilities-override.yaml
bundle/tests/scorecard/kuttl/security-context/04-restore-default.yaml
scripts/e2e-kind.sh

- Need to update k8s.gcr.io to registry.k8s.io
Related https://github.com/application-stacks/runtime-component-operator/issues/502

Update k8s.gcr.io to registry.k8s.io

---

Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- To update sample app image to Multi-Arch
Related https://github.com/WASdev/websphere-liberty-operator/issues/447

Update sample app to Multi-Arch version

---

scripts/pipeline/release.sh

- Same fix as WLO PR: https://github.com/WASdev/websphere-liberty-operator/pull/464/files
Fixes #

Remove arch from release script

---

scripts/e2e-kind.sh

- Fix e2e tests for kind cluster
Fixes #

Fix reference to operator deployment file for kind e2e test

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manifests/description.md

- Update description and features
Fixes #

Update operator readme

---

internal/deploy/kustomize/1.2.0/README.adoc
internal/deploy/kustomize/1.2.0/base/kustomization.yaml
internal/deploy/kustomize/1.2.0/base/open-liberty-crd.yaml
internal/deploy/kustomize/1.2.0/base/open-liberty-operator.yaml
internal/deploy/kustomize/1.2.0/base/open-liberty-roles.yaml
internal/deploy/kustomize/1.2.0/examples/watch-all-namespaces/kustomization.yaml
internal/deploy/kustomize/1.2.0/examples/watch-all-namespaces/olo-ns.yaml
internal/deploy/kustomize/1.2.0/examples/watch-another-namespace/kustomization.yaml
internal/deploy/kustomize/1.2.0/examples/watch-another-namespace/olo-ns2/kustomization.yaml
internal/deploy/kustomize/1.2.0/examples/watch-another-namespace/olo-ns2/olo-deployment.yaml
internal/deploy/kustomize/1.2.0/examples/watch-another-namespace/olo-ns2/olo-roles.yaml
internal/deploy/kustomize/1.2.0/examples/watch-another-namespace/olo-ns2/olo-sa.yaml
internal/deploy/kustomize/1.2.0/examples/watch-another-namespace/olo-watched-ns2/kustomization.yaml
internal/deploy/kustomize/1.2.0/examples/watch-another-namespace/olo-watched-ns2/watched-roles.yaml
internal/deploy/kustomize/1.2.0/examples/watch-own-namespace/kustomization.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-all-namespaces/cluster-roles.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-all-namespaces/kustomization.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-all-namespaces/olo-all-namespaces.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/kustomization.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-ns/kustomization.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-ns/olo-deployment.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-ns/olo-roles.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-ns/olo-sa.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-watched-ns/kustomization.yaml
internal/deploy/kustomize/1.2.0/overlays/watch-another-namespace/olo-watched-ns/watched-roles.yaml

- Add kustomize install files for 1.2.0 (internal til validation)
- 
Fixes #

Add kustomize install files for 1.2.0 (internal til validation)

---

Makefile
config/kubectl/crd/kustomization.yaml
config/kubectl/operator/kustomization.yaml
config/kubectl/operator/patches/delete-namespace.yaml
config/kubectl/rbac-watch-all/kustomization.yaml
config/kubectl/rbac-watch-all/patches/delete-service-account.yaml
config/kubectl/rbac-watch-another/kustomization.yaml
config/kubectl/rbac-watch-another/patches/delete-service-account.yaml
internal/deploy/kubectl/openliberty-app-crd.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kubectl/openliberty-app-rbac-watch-all.yaml
internal/deploy/kubectl/openliberty-app-rbac-watch-another.yaml
internal/deploy/kubectl/readme.adoc

- Adds in the generator files for the kubectl install option and the generated output from an initial run 
Fixes #

Added kubectl install generator and output

---

internal/deploy/1.2.0/kubectl/openliberty-app-crd.yaml
internal/deploy/1.2.0/kubectl/openliberty-app-operator.yaml
internal/deploy/1.2.0/kubectl/openliberty-app-rbac-watch-all.yaml
internal/deploy/1.2.0/kubectl/openliberty-app-rbac-watch-another.yaml
internal/deploy/1.2.0/kubectl/readme.adoc

- Add kubectl-install artifacts for 1.2.0 (internal till validation)
- 
Fixes #

Add kubectl-install artifacts for 1.2.0 (internal till validation)

---

doc/user-guide-v1.adoc

- Add networkPolicy section to user-guide-v1.adoc
Fixes #

Add networkPolicy to user-guide-v1.adoc

---

bundle/tests/scorecard/kuttl/basic/00-assert.yaml
bundle/tests/scorecard/kuttl/dump/01-assert.yaml
bundle/tests/scorecard/kuttl/trace/01-assert.yaml

As per issue application-stacks/runtime-component-operator#489

Add test for versions.reconciled

---

bundle/tests/scorecard/kuttl/image-stream/00-assert.yaml
bundle/tests/scorecard/kuttl/image-stream/01-assert.yaml
bundle/tests/scorecard/kuttl/image-stream/02-assert.yaml
bundle/tests/scorecard/kuttl/image-stream/03-assert.yaml
bundle/tests/scorecard/kuttl/image-stream/04-assert.yaml
bundle/tests/scorecard/kuttl/kuttl-test.yaml
bundle/tests/scorecard/kuttl/probe/01-assert.yaml
bundle/tests/scorecard/kuttl/probe/02-assert.yaml
bundle/tests/scorecard/kuttl/pullpolicy/00-always.yaml
bundle/tests/scorecard/kuttl/pullpolicy/00-assert.yaml
bundle/tests/scorecard/kuttl/pullpolicy/01-assert.yaml
bundle/tests/scorecard/kuttl/pullpolicy/02-assert.yaml
bundle/tests/scorecard/kuttl/pullpolicy/03-assert.yaml

- Fixes several of the tests that were failing on Z and P

Update tests so they are more robust on Z and P archs

---

Makefile
scripts/acceptance-test.sh
scripts/pipeline/ocp-cluster-e2e.sh
scripts/pipeline/runTest.sh

- Checks that the correct operator is installed during the acceptance-test stage of the onepipline build

Check that installed version of operator is the correct version

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- Update sample app
- PR for https://github.com/OpenLiberty/open-liberty-operator/issues/445
Fixes #

Update sample app

---

.one-pipeline-archive.yaml
.one-pipeline-cd.yaml
scripts/pipeline/runTest.sh

Update OLO with the equivalent changes from the following WLO PRs:
- https://github.com/WASdev/websphere-liberty-operator/pull/512
- https://github.com/WASdev/websphere-liberty-operator/pull/520
Fixes #

Pipeline updates - add env_id and update to new signing image

---

Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- Addresses https://github.com/OpenLiberty/open-liberty-operator/issues/448
Fixes #

Added operator image to related images

---

.one-pipeline-archive.yaml
.one-pipeline.yaml
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- Update sample app
- Skip detect-secrets (similar to WLO PR https://github.com/WASdev/websphere-liberty-operator/pull/536)
Fixes #

Update sample app + skip new detect-secrets stage 

---

doc/observability-deployment.adoc
doc/openshift-logging-rhocp_4.7+.adoc
doc/openshift-monitoring.adoc

- Need to update the RHOCP versions in the Observability documentations.
N/A

Update RHOCP version in Observability documentations

---

go.mod
go.sum

Includes fix for insecureEdgeTerminiationPolicy
For issue #463

Pull in latest RCO utils

---

Dockerfile
api/v1/openlibertyapplication_types.go
bundle/manifests/apps.openliberty.io_openlibertyapplications.yaml
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/crd/bases/apps.openliberty.io_openlibertyapplications.yaml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/assets/create_ltpa_keys.sh
controllers/ltpa_keys_sharing.go
controllers/openlibertyapplication_controller.go
internal/deploy/kubectl/openliberty-app-crd.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kubectl/openliberty-app-rbac-watch-all.yaml
internal/deploy/kubectl/openliberty-app-rbac-watch-another.yaml
internal/deploy/kustomize/daily/base/open-liberty-crd.yaml
internal/deploy/kustomize/daily/base/open-liberty-roles.yaml
internal/deploy/kustomize/daily/overlays/watch-all-namespaces/cluster-roles.yaml
internal/deploy/kustomize/daily/overlays/watch-another-namespace/olo-watched-ns/watched-roles.yaml
utils/utils.go

- Adds LTPA key sharing support to OpenLibertyApplication with boolean flag `.spec.manageLTPA`
- Adds missing manifests for topology spread constraints

Add LTPA key sharing support

---

api/v1/zz_generated.deepcopy.go
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
go.sum
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- Update getting-started sample app image
- 
Fixes #

Update getting-started sample app image

---

doc/user-guide-v1.adoc

Docs for issue:
https://github.com/OpenLiberty/open-liberty-operator/issues/462

Update user guide for service account changes

---

doc/observability-deployment.adoc
doc/openshift-logging-rhocp_4.7+.adoc
doc/openshift-monitoring.adoc

Update versions for observability guides to 4.14

---

Dockerfile
Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
index.Dockerfile
utils/utils.go

- Update operator version to 1.3.1
PR for https://github.com/OpenLiberty/open-liberty-operator/issues/528
Fixes #

Update operator version to 1.3.1

---

config/samples/apps.openliberty.io_v1_openlibertydumps.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertydumps.yaml
doc/user-guide-v1.adoc

Change sample dump defaults

---

controllers/openlibertyapplication_controller.go
go.mod
go.sum

And add necessary controller changes
OLO portion of application-stacks/runtime-component-operator#299

Get latest RCO for route hostname fix

---

Makefile

Related to https://github.com/application-stacks/runtime-component-operator/pull/619

Remove unused args for e2e-ocp.sh

---

controllers/openlibertyapplication_controller.go
go.mod
go.sum

Picks up a change to move some code into common utils
Based on https://github.com/application-stacks/runtime-component-operator/pull/618

Update to latest RCO

---

api/v1/openlibertyapplication_types.go
api/v1beta2/openlibertyapplication_types.go
bundle/manifests/apps.openliberty.io_openlibertyapplications.yaml
config/crd/bases/apps.openliberty.io_openlibertyapplications.yaml
go.mod
go.sum
internal/deploy/kubectl/openliberty-app-crd.yaml
internal/deploy/kustomize/daily/base/open-liberty-crd.yaml

Address https://github.com/WASdev/websphere-liberty-operator/issues/474

Add a warning when manageTLS=true but service port=9080

---

Makefile
bundle/manifests/apps.openliberty.io_openlibertyapplications.yaml
bundle/manifests/apps.openliberty.io_openlibertydumps.yaml
bundle/manifests/apps.openliberty.io_openlibertytraces.yaml
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/crd/bases/apps.openliberty.io_openlibertyapplications.yaml
config/crd/bases/apps.openliberty.io_openlibertydumps.yaml
config/crd/bases/apps.openliberty.io_openlibertytraces.yaml
config/rbac/role.yaml
internal/deploy/kubectl/openliberty-app-crd.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kubectl/openliberty-app-rbac-watch-all.yaml
internal/deploy/kubectl/openliberty-app-rbac-watch-another.yaml
internal/deploy/kustomize/daily/base/open-liberty-crd.yaml
internal/deploy/kustomize/daily/base/open-liberty-roles.yaml
internal/deploy/kustomize/daily/overlays/watch-all-namespaces/cluster-roles.yaml
internal/deploy/kustomize/daily/overlays/watch-another-namespace/olo-watched-ns/watched-roles.yaml

Update controller-gen version

---

Dockerfile
Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
catalog.Dockerfile
config/manager/manager.yaml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
go.mod
go.sum
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml
utils/utils.go

- Update Operator version to 1.3.2 (https://github.com/OpenLiberty/open-liberty-operator/issues/582)
- Update RCO module
- Update getting-started sample application
Fixes #

Update version to 1.3.2, update RCO module and sample app

---

LICENSE
README.adoc
README.md
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- Update sample app 
- Update license to EPL 2.0 to match Open Liberty runtime
Fixes #

Update sample app and license

---

Dockerfile
Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
catalog.Dockerfile
config/manager/manager.yaml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
go.mod
go.sum
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml
utils/utils.go

- Update version to 1.3.3
- Add annotations required for RH certified pipeline
- Update getting-started sample image
- Update RCO to use targetPort with network policy
Fixes #

Update version to 1.3.3, update sample app and RCO package

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- Update getting-started sample app
Fixes #

Update getting-started sample app

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
doc/user-guide-v1.adoc
scripts/dev.sh

- To remove deprecated features
Related https://github.com/OpenLiberty/open-liberty-operator/issues/553

Remove the usage of deprecated features

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
go.mod
go.sum
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- To comply with restricted:v1.24
Fixes #

Set RuntimeDefault as default for SeccompProfile

---

go.mod
go.sum

- Update go to v1.23
- 
Fixes #

Go version update to 1.23

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
go.mod
go.sum
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- Update getting-started sample - https://github.com/OpenLiberty/open-liberty-operator/issues/619
- Update RCO module to pickup DNS names changes (headless and wildcard entries) - https://github.com/OpenLiberty/open-liberty-operator/issues/605
Fixes #

Update getting-started sample + DNS entries update

---

internal/controller/semeru_compiler.go

- Fixes the name of the custom Issuer to match OLO docs
Fixes #

Fix custom Issuer name in Semeru Cloud Compiler

---

internal/controller/openlibertyapplication_controller.go

Move some unnecessary messages to debug level
Follow up to #638

Reduce info log messages

---

go.mod
go.sum

- Update RCO module to include default log level (https://github.com/application-stacks/runtime-component-operator/pull/669)
Fixes #

Update RCO to include default log level

---

doc/user-guide-v1.adoc

- Document smart reconciliation and operator ConfigMap configurations
Related https://github.com/OpenLiberty/open-liberty-operator/issues/669

Doc for smart reconciliation

---

Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
config/crd/kustomization.yaml
config/default/kustomization.yaml
config/kubectl/crd/kustomization.yaml
config/kubectl/operator/kustomization.yaml
config/kubectl/rbac-watch-all/kustomization.yaml
config/kubectl/rbac-watch-another/kustomization.yaml
config/kustomize/crd/kustomization.yaml
config/kustomize/operator/kustomization.yaml
config/kustomize/roles/kustomization.yaml
config/kustomize/watch-all/kustomization.yaml
config/kustomize/watch-another/kustomization.yaml
config/manifests/kustomization.yaml
config/scorecard/kustomization.yaml

- Updating Kustomize to v5
https://github.com/application-stacks/runtime-component-operator/issues/684

Update to Kustomize v5

---

Dockerfile

Revert Dockerfile user to 65532

---

doc/observability-deployment.adoc
doc/openshift-logging-rhocp_4.17+.adoc
doc/openshift-monitoring.adoc

Updating observability docs for 4.18.

Update observability docs for RHOCP 4.18

---

Dockerfile
Makefile

Use securityUtility from 25.0.0.1

---

bundle/manifests/open-liberty.clusterserviceversion.yaml
config/manager/manager.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml

- Update getting-started sample
Fixes #

Update getting-started sample

---

doc/user-guide-v1.adoc

- Update smart reconciliation documentation
Fixes #

Update smart reconciliation doc

---

.ci-orchestrator/open-liberty-operator-build.yml

As ubuntu 20 is going out of support

Move to building p and z on ubuntu 22

---

internal/controller/openlibertydump_controller.go

- Update dump file name to be compatible with all platforms including Windows
- https://github.com/WASdev/websphere-liberty-operator/issues/745
Fixes #

Update dump file name to be compatible with all platforms including Windows

---

Dockerfile
Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
catalog.Dockerfile
config/manager/manager.yaml
config/manifests/bases/open-liberty.clusterserviceversion.yaml
config/samples/apps.openliberty.io_v1_openlibertyapplications.yaml
config/samples/apps.openliberty.io_v1beta2_openlibertyapplications.yaml
go.mod
go.sum
internal/deploy/kubectl/openliberty-app-operator.yaml
internal/deploy/kustomize/daily/base/open-liberty-operator.yaml
utils/utils.go

- Updates for OLO 1.4.3
Fixes #

Updates for OLO 1.4.3

---

doc/user-guide-v1.adoc

Found a missing section as part of issue
https://github.com/WASdev/websphere-liberty-operator/issues/746

Sync seccomp profile docs with WLO

---

Dockerfile
Makefile
bundle/manifests/open-liberty.clusterserviceversion.yaml
catalog.Dockerfile
config/manifests/bases/open-liberty.clusterserviceversion.yaml
utils/utils.go

- Update OLO version to 1.4.4
Fixes #

Update OLO version to 1.4.4

---

doc/observability-deployment.adoc
doc/openshift-logging-rhocp_4.7-4.16.adoc
doc/openshift-monitoring.adoc

- remove references to unsupported versions of OCP

remove references to unsupported versions

---

doc/user-guide-v1.adoc

OLO portion of https://github.com/OpenLiberty/open-liberty-operator/issues/749

Add docs for '.spec.serviceAccount.skipPullSecretValidation'

---

doc/user-guide-v1.adoc

Document performance data usage
